version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nitechhub_api
    volumes:
      - /usr/src/node_modules
      - .:/usr/src/app
    command: npm run start
    expose:
      - 3000
    ports:
      - "3000:3000"
